server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.example.monthsettledemo.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true

